export const refs = {
  galleryMovies: document.querySelector('.gallery__list'),
  formSearch: document.querySelector('.header__form'),
  modal: document.querySelector('.modal__content'),
  modalContainer: document.querySelector('.modal'),
  modalBackdrop: document.querySelector('.backdrop'),
  closeModalBtn: document.querySelector('.modal-close'),
  notification: document.querySelector('.header__notification'),
  btnAddWatched: document.querySelector('.js-add-watched'),
  btnAddqueue: document.querySelector('js-add-queue'),
  wrapperBtnUP: document.querySelector('.btn-up-wrapper'),
  btnUp: document.querySelector('.btn-up-wrapper__btn'),
  body: document.querySelector('body'),
  link: document.querySelector('.footer__link'),
  modalBackdropTrailer: document.querySelector('.backdrop-trailer'),
  libraryLink: document.querySelector('.js-library-link'),
  btnLibraryQueue: document.querySelector('.queue__btn'),
  btnLibraryWatched: document.querySelector('.watched__btn'),
  libraryBtnsList: document.querySelector('.library__btn-list'),
  libraryGallery: document.querySelector('.library-gallery__list'),
};
